spring:
  application:
    name: ten-comments

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    me.choijunha.youtubecommentproject: DEBUG

spring.devtools:
  livereload:
    enabled: true
  restart:
    enabled: true

youtube:
  api:
    key: ${YOUTUBE_API_KEY}